version: '3'
services:
    ${CIRCLE_PROJECT_REPONAME}:
        image: nginx
        volumes:
            - /home/ec2-user/nginx/conf.d:/etc/nginx/conf.d
            - /home/ec2-user/nginx/ssl:/etc/nginx/ssl
        ports:
            - "80:80"
            - "443:443"
