version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ""

      - run: echo "Hello World"
      - run: echo $CIRCLE_PROJECT_REPONAME
      - run: envsubst '${CIRCLE_PROJECT_REPONAME}' < deploy.sh > real_deploy.sh
      - run: ssh -o StrictHostKeyChecking=no $USER@$HOST
